server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "blog_db"
  sslmode: "disable"

jwt:
  secret: "my-secret-key-here"
  expiry: "24h"
