# Server Configuration (non-sensitive)
server:
  port: "8080"
  mode: "debug"

# Database Configuration (sensitive values should be in .env)
database:
  host: ""
  port: ""
  user: ""
  password: ""
  dbname: ""
  sslmode: ""

# JWT Configuration (sensitive values should be in .env)
jwt:
  secret: ""
  expiry: ""
